name: CI Pipeline Laboratory

on:
   push:
   pull_request:

jobs:
    validate:
      name: Validation
      runs-on: ubuntu-latest
    
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
           
        - name: Validate Makefile
          run: make hello
    
    docker:
      name: Container
      needs: validate
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Execute Makefile
          run: make build
               make run






