name: CI Pipeline Laboratory

on:
   push:
   pull_request:

permissions:
  contents: read
  packages: write

jobs:
    validate:
      name: Validation
      runs-on: ubuntu-latest
    
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
           
        - name: Validate Makefile
          run: make hello
    
    docker:
      name: Container
      needs: validate
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Execute Makefile Build
          run: make build

        - name: Execute Tag to change name image
          run: docker tag devops-laboratory ghcr.io/katherin8/plataform-devops-laboratory:latest

        - name: Execute Login in Docker GHCR
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Execute Docker push in Registry
          run: docker push ghcr.io/katherin8/plataform-devops-laboratory:latest






